paths:
  sample_profile: hg002hifi
  pbsim_path: /home/schmitzmf/pbsim3
  hifiasm_path: /home/schmitzmf/hifiasm_020/
  raven_path: /home/schmitzmf/heron-raven
  herro_path: /home/schmitzmf/herro_folder
  hifiasm_dump: /home/schmitzmf/scratch/dumps/hifiasm_dump_4
  raft_path: /home/schmitzmf/RAFT
  centromere_coords: /home/schmitzmf/diploid_gnnome/data/centromere_coordinates_same_len.yml
gen_config:
  depth: 20
  threads: 16
  assembler: hifiasm
  diploid: True
  real: False
  prep_decoding: False
  raft: False
gen_steps:
  sample_reads: False
  create_graphs: False
  parse_gfa: True
  pile-o-gram: False
  diploid_features: False
  ground_truth: False
  ml_graphs: False

training:
  chr1: 1 #i002c_v04_multi_21.chr1
  chr2: 1 #i002c_v04_multi_21.chr2
validation:
