training:
  seed: 1
  num_epochs: 10000
  num_gnn_layers: 8
  num_trans_layers: 3
  hidden_features: 128
  emb_dim: 64
  direct_ftrs: False
  use_standard_attention: False
  projection_dim: 16
  node_features: 4
  gnn_dropout: 0.0
  lr: 0.0001
  aux_loss_weight: 0.02
  wandb_mode: 'online'
  decay: 0.95
  patience: 2
  alpha: 0.0
  compute_metrics_every: 100
  visualize_during_training: False
  only_scaffold: False
  only_phase: False
  batch_size: 4096
  evaluate: True
  visualize: False
  norm: 'pair'
  max_nodes: 10000  